### ISSUE TITLE
[Query] Any way to forward web links from the text document instead of individually mentioning them

### ISSUE THREAD

**Issue by bheeshmpita** [Ailothaen/RedditArchiver-standalone#6]
such that all the URL can be pasted in a document instead of giving them individually?

**Comment by Ailothaen** [comment]
Hello!
I just pushed an update that allows to use a `-I`/`--file` options to supply URLs or IDs in a file (which can indeed be useful for automated processes). This option can be used multiple times. Does it fit your need?

**Comment by bheeshmpita** [comment]
> Does it fit your need?

Exactly and (unrelated to previous query) is there any way i can get the images in the post as well.

**Comment by Ailothaen** [comment]
As now, there is no way to do that with RedditArchiver, because it focuses more on the text content (both from the submission and comments) rather than the media content. If you want to get images and videos from a post, I recommend using [mikf/gallery-dl](https://github.com/mikf/gallery-dl) (which itself uses [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp) for videos)
